
spring:
  application:
    name: redis-spring
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${DB_NAME:postgres}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  sql:
    init:
      mode: always # run schema.sql/data.sql at startup (optional)

city:
  service:
    url: http://localhost:3030/open-city-api/

redis:
  caches:
    math-fib:
      cache-name: "math:fib"
      ttl: 10000 # milliseconds
    other-cache:
      cache-name: "other:key"
      ttl: 120000
    weather:
        cache-name: "weather:city"
        ttl: 300000
    weather-reactive:
        cache-name: "weather:city-reactive"
        ttl: 300000

server:
  port: 8080

logging:
  level:
    org.springframework.web.reactive.socket: DEBUG
    com.spring.websocketchat: DEBUG
